# módulo destinado a valores numéricos que permanecen constantes e influyen
# en los resultados de la simulación.

# importar como par o parámetros directamanete.

# nebiland
PATH_ARRIVALS = "arrivals.csv"
PATH_ASSOCIATIONS = "associations.csv"
PATH_ATTRACTIONS = "attractions.csv"
PATH_RESTAURANTS = "restaurants.csv"
DIAS_SIMULACION = ("Lunes", "Martes", "Miercoles",  "Jueves", "Viernes",
                   "Sábado", "Domingo")
HORA_CIERRE = (19, 0)
HORA_ABRIR = (10, 0)
NUMERO_ITERACIONES = 5
MULTIPLICANDO_CAPACIDAD = 1.2

#
TIEMPO_DECIDIR = (0, 10)

# atracciones
TIEMPO_MAXIMO_LIMPIEZA = 10
SUCIEDAD_INICIAL = 0
TIEMPO_FALLA_MINIMA = 1
SUCIEDAD_POR_VOMITO = 40
SUCIEDAD_POR_PERSONA = 1

# restaurants
TASA_PREPARACION_ADULTOS = 1/6
TASA_PREPARACION_NINOS = 1/4
TIEMPO_MINIMO_PREPARACION = 1
TIEMPO_MAXIMO_PREPARACION = 30

# clientes
MU_ADULTO = 170
MU_NINO = 120
SIGMA_ADULTO = 8
SIGMA_NINO = 15
ALTURA_MINIMA = 60
ALTURA_MAXIMA = 190

ENERGIA_INICIAL = 1  # también es la energía máxima
ENERGIA_MINIMA = 0

NAUSEA_INICIAL = 0
RANGO_VOMITO = 90
NAUSEA_VOMITO = 50  # después del vómito
NAUSEA_MAXIMA = 150
AUMENTO_NAUSEA_ADULTO = 5
AUMENTO_NAUSEA_NINO = 10
AUMENTO_NAUSEA_RESTAURANT = 30
PROBABILIDAD_VOMITO = 0.6

HAMBRE_INICIAL = (0.1, 0.25)
HAMBRE_MINIMA = 0
HAMBRE_MAXIMA = 1

MULTIPLICADOR_PACIENCIA = 30
SUMANDO_PACIENCIA = 10
SIGMA_PACIENCIA = 5
MINIMA_PACIENCIA = 3
MAXIMA_PACIENCIA = 100

EDAD_NINOS = (1, 17)
EDAD_ADULTOS = (18, 120)

DISMINUCION_HAMBRE = 0.06
AUMENTO_ENERGIA = 0.2

DISMINUCION_ENERGIA_ADULTOS = 0.15
AUMENTO_HAMBRE_ADULTOS = 0.05
DISMINUCION_ENERGIA_NINOS = 0.05
AUMENTO_HAMBRE_NINOS = 0.1

ENERGIA_LLORAR_NINO = 0.1
ENRGIA_LLORAR_ADULTO = 0.2

ENERGIA_IRSE = 0.1
PROBABILIDAD_IRSE = 0.5


# empleados
# se suma la probabilidad anterior, al final se usa else (máximo debe ser 1)
PROBABILIDADES_COLACION = (0.05, 0.1, 0.4, 0.6, 0.7, 0.8, 0.85, 0.9)
HORAS_COLACION = ((10, 0), (11, 0), (12, 0), (13, 0), (14, 0),
                  (15, 0), (16, 0), (17, 0), (18, 0))

PROPORCION_LIMPIADORES = 2
PROPORCION_TECNICOS = 3
TRASLADO_LIMPIADOR = 15

TRASLADO_TECNICO = 15
TIEMPO_REPARACION = 20

# toma de decisiones
PROBABILIDAD_HACER_FILA = 0.7
MULTIPLICANDO_HAMBRE = 0.3

# Eventos externos
TASA_LLUVIA = 0.05
TIPOS_QUE_CIERRAN = {"acuatica"}
DIAS_COLEGIO = {"Sábado"}
PROBABILIDAD_DIA_COLEGIO = 0.5
DIAS_RUZILAND = {"Lunes"}
PROBABILIDAD_INVASION = 0.125  # lunes por medio
PROBABILIDAD_RETIRARSE = 0.4
